[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci', 'npm run build']

[start]
cmd = '/start.sh'
